name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Use the latest version that supports Node.js 20
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3  # Use the latest version that supports Node.js 20
        with:
          hugo-version: "latest"

      - name: Build
        run: hugo --minify

      - name: Create .nojekyll
        run: echo "" > ./public/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4  # Use the latest version that supports Node.js 20
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: ./public

